#ifndef CLIPPING_RENENGINE_SFW
#define CLIPPING_RENENGINE_SFW

typedef enum frustum_plane
{
  LEFT_FRUSTUM_PLANE,
  RIGHT_FRUSTUM_PLANE,
  TOP_FRUSTUM_PLANE,
  BOTTOM_FRUSTUM_PLANE,
  NEAR_FRUSTUM_PLANE,
  FAR_FRUSTUM_PLANE,
};

#endif
